/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/solid-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiRegistryPublicIndexServerRouteImport } from './routes/api/registry/public/index'
import { ServerRoute as ApiRegistryPublicNameServerRouteImport } from './routes/api/registry/public/$name'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistryPublicIndexServerRoute =
  ApiRegistryPublicIndexServerRouteImport.update({
    id: '/api/registry/public/',
    path: '/api/registry/public/',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiRegistryPublicNameServerRoute =
  ApiRegistryPublicNameServerRouteImport.update({
    id: '/api/registry/public/$name',
    path: '/api/registry/public/$name',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/registry/public/$name': typeof ApiRegistryPublicNameServerRoute
  '/api/registry/public': typeof ApiRegistryPublicIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/registry/public/$name': typeof ApiRegistryPublicNameServerRoute
  '/api/registry/public': typeof ApiRegistryPublicIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/registry/public/$name': typeof ApiRegistryPublicNameServerRoute
  '/api/registry/public/': typeof ApiRegistryPublicIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/registry/public/$name' | '/api/registry/public'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/registry/public/$name' | '/api/registry/public'
  id: '__root__' | '/api/registry/public/$name' | '/api/registry/public/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiRegistryPublicNameServerRoute: typeof ApiRegistryPublicNameServerRoute
  ApiRegistryPublicIndexServerRoute: typeof ApiRegistryPublicIndexServerRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/solid-start/server' {
  interface ServerFileRoutesByPath {
    '/api/registry/public/': {
      id: '/api/registry/public/'
      path: '/api/registry/public'
      fullPath: '/api/registry/public'
      preLoaderRoute: typeof ApiRegistryPublicIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/registry/public/$name': {
      id: '/api/registry/public/$name'
      path: '/api/registry/public/$name'
      fullPath: '/api/registry/public/$name'
      preLoaderRoute: typeof ApiRegistryPublicNameServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiRegistryPublicNameServerRoute: ApiRegistryPublicNameServerRoute,
  ApiRegistryPublicIndexServerRoute: ApiRegistryPublicIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
