/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/solid-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiRegistryIndexServerRouteImport } from './routes/api/registry/index'
import { ServerRoute as ApiRegistryNameServerRouteImport } from './routes/api/registry/$name'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistryIndexServerRoute = ApiRegistryIndexServerRouteImport.update({
  id: '/api/registry/',
  path: '/api/registry/',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiRegistryNameServerRoute = ApiRegistryNameServerRouteImport.update({
  id: '/api/registry/$name',
  path: '/api/registry/$name',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login'
  id: '__root__' | '/' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
}
export interface FileServerRoutesByFullPath {
  '/api/registry/$name': typeof ApiRegistryNameServerRoute
  '/api/registry': typeof ApiRegistryIndexServerRoute
}
export interface FileServerRoutesByTo {
  '/api/registry/$name': typeof ApiRegistryNameServerRoute
  '/api/registry': typeof ApiRegistryIndexServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/registry/$name': typeof ApiRegistryNameServerRoute
  '/api/registry/': typeof ApiRegistryIndexServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/registry/$name' | '/api/registry'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/registry/$name' | '/api/registry'
  id: '__root__' | '/api/registry/$name' | '/api/registry/'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiRegistryNameServerRoute: typeof ApiRegistryNameServerRoute
  ApiRegistryIndexServerRoute: typeof ApiRegistryIndexServerRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/solid-start/server' {
  interface ServerFileRoutesByPath {
    '/api/registry/': {
      id: '/api/registry/'
      path: '/api/registry'
      fullPath: '/api/registry'
      preLoaderRoute: typeof ApiRegistryIndexServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/registry/$name': {
      id: '/api/registry/$name'
      path: '/api/registry/$name'
      fullPath: '/api/registry/$name'
      preLoaderRoute: typeof ApiRegistryNameServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiRegistryNameServerRoute: ApiRegistryNameServerRoute,
  ApiRegistryIndexServerRoute: ApiRegistryIndexServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
