import tailwindcss from "@tailwindcss/vite";
import dts from "unplugin-dts/vite";
import { defineConfig } from "vite";
import solid from "vite-plugin-solid";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  build: {
    lib: {
      entry: {
        "ui/accordion": "src/ui/accordion.tsx",
        "ui/alert-dialog": "src/ui/alert-dialog.tsx",
        "ui/alert": "src/ui/alert.tsx",
        "ui/avatar": "src/ui/avatar.tsx",
        "ui/badge": "src/ui/badge.tsx",
        "ui/breadcrumb": "src/ui/breadcrumb.tsx",
        "ui/button": "src/ui/button.tsx",
        "ui/calendar": "src/ui/calendar.tsx",
        "ui/card": "src/ui/card.tsx",
        "ui/checkbox": "src/ui/checkbox.tsx",
        "ui/collapsible": "src/ui/collapsible.tsx",
        "ui/combobox": "src/ui/combobox.tsx",
        "ui/command": "src/ui/command.tsx",
        "ui/commandbox": "src/ui/commandbox.tsx",
        "ui/container": "src/ui/container.tsx",
        "ui/context-menu": "src/ui/context-menu.tsx",
        "ui/date-picker": "src/ui/date-picker.tsx",
        "ui/dialog": "src/ui/dialog.tsx",
        "ui/drawer": "src/ui/drawer.tsx",
        "ui/dropdown-menu": "src/ui/dropdown-menu.tsx",
        "ui/flex": "src/ui/flex.tsx",
        "ui/form": "src/ui/form.tsx",
        "ui/grid": "src/ui/grid.tsx",
        "ui/hover-card": "src/ui/hover-card.tsx",
        "ui/image": "src/ui/image.tsx",
        "ui/input-otp": "src/ui/input-otp.tsx",
        "ui/input": "src/ui/input.tsx",
        "ui/kbd": "src/ui/kbd.tsx",
        "ui/label": "src/ui/label.tsx",
        "ui/link": "src/ui/link.tsx",
        "ui/menubar": "src/ui/menubar.tsx",
        "ui/navigation-menu": "src/ui/navigation-menu.tsx",
        "ui/number-field": "src/ui/number-field.tsx",
        "ui/pagination": "src/ui/pagination.tsx",
        "ui/popover": "src/ui/popover.tsx",
        "ui/progress": "src/ui/progress.tsx",
        "ui/radio-group": "src/ui/radio-group.tsx",
        "ui/resizable": "src/ui/resizable.tsx",
        "ui/select": "src/ui/select.tsx",
        "ui/separator": "src/ui/separator.tsx",
        "ui/sheet": "src/ui/sheet.tsx",
        "ui/sidebar": "src/ui/sidebar.tsx",
        "ui/skeleton": "src/ui/skeleton.tsx",
        "ui/slider": "src/ui/slider.tsx",
        "ui/sonner": "src/ui/sonner.tsx",
        "ui/switch": "src/ui/switch.tsx",
        "ui/table": "src/ui/table.tsx",
        "ui/tabs": "src/ui/tabs.tsx",
        "ui/text-field": "src/ui/text-field.tsx",
        "ui/textarea": "src/ui/textarea.tsx",
        "ui/toggle-group": "src/ui/toggle-group.tsx",
        "ui/toggle": "src/ui/toggle.tsx",
        "ui/tooltip": "src/ui/tooltip.tsx",
        "ui/typography": "src/ui/typography.tsx",
        form: "src/form/index.ts",
        hooks: "src/hooks/index.ts",
      },
      formats: ["es"],
      fileName: (_, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      external: [
        "solid-js",
        "solid-js/store",
        "solid-js/web",
        "tailwindcss",
        /lucide-solid/,
      ],
      output: {
        globals: {
          "solid-js": "Solid",
          "solid-js/web": "SolidWeb",
          "solid-js/store": "SolidStore",
        },
      },
    },
  },
  resolve: {
    conditions: ["development", "solid", "browser"],
  },
  plugins: [
    tsconfigPaths(),
    tailwindcss(),
    solid(),
    dts({ tsconfigPath: "./tsconfig.build.json" }),
  ],
});
