import tailwindcss from "@tailwindcss/vite";
import dts from "unplugin-dts/vite";
import { defineConfig } from "vite";
import solid from "vite-plugin-solid";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  build: {
    lib: {
      entry: {
        index: "src/ui/index.ts",
        accordion: "src/ui/accordion.tsx",
        "alert-dialog": "src/ui/alert-dialog.tsx",
        alert: "src/ui/alert.tsx",
        avatar: "src/ui/avatar.tsx",
        badge: "src/ui/badge.tsx",
        breadcrumb: "src/ui/breadcrumb.tsx",
        button: "src/ui/button.tsx",
        calendar: "src/ui/calendar.tsx",
        card: "src/ui/card.tsx",
        checkbox: "src/ui/checkbox.tsx",
        collapsible: "src/ui/collapsible.tsx",
        combobox: "src/ui/combobox.tsx",
        command: "src/ui/command.tsx",
        commandbox: "src/ui/commandbox.tsx",
        container: "src/ui/container.tsx",
        "context-menu": "src/ui/context-menu.tsx",
        "date-picker": "src/ui/date-picker.tsx",
        dialog: "src/ui/dialog.tsx",
        drawer: "src/ui/drawer.tsx",
        "dropdown-menu": "src/ui/dropdown-menu.tsx",
        flex: "src/ui/flex.tsx",
        form: "src/ui/form.tsx",
        grid: "src/ui/grid.tsx",
        "hover-card": "src/ui/hover-card.tsx",
        image: "src/ui/image.tsx",
        "input-otp": "src/ui/input-otp.tsx",
        input: "src/ui/input.tsx",
        kbd: "src/ui/kbd.tsx",
        label: "src/ui/label.tsx",
        link: "src/ui/link.tsx",
        menubar: "src/ui/menubar.tsx",
        "navigation-menu": "src/ui/navigation-menu.tsx",
        "number-field": "src/ui/number-field.tsx",
        pagination: "src/ui/pagination.tsx",
        popover: "src/ui/popover.tsx",
        progress: "src/ui/progress.tsx",
        "radio-group": "src/ui/radio-group.tsx",
        resizable: "src/ui/resizable.tsx",
        select: "src/ui/select.tsx",
        separator: "src/ui/separator.tsx",
        sheet: "src/ui/sheet.tsx",
        sidebar: "src/ui/sidebar.tsx",
        skeleton: "src/ui/skeleton.tsx",
        slider: "src/ui/slider.tsx",
        sonner: "src/ui/sonner.tsx",
        switch: "src/ui/switch.tsx",
        table: "src/ui/table.tsx",
        tabs: "src/ui/tabs.tsx",
        "text-field": "src/ui/text-field.tsx",
        textarea: "src/ui/textarea.tsx",
        "toggle-group": "src/ui/toggle-group.tsx",
        toggle: "src/ui/toggle.tsx",
        tooltip: "src/ui/tooltip.tsx",
        typography: "src/ui/typography.tsx",
      },
      formats: ["es"],
      fileName: (_, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      external: [
        "effect",
        /@effect/,
        "solid-js",
        "solid-js/web",
        "tailwindcss",
      ],
      output: {
        globals: {
          "@effect/platform-bun/BunContext": "BunContext",
          "@effect/platform/FileSystem": "FileSystem",
          "@effect/platform/Path": "Path",
          "effect/Cause": "Cause",
          "effect/Data": "Data",
          "effect/Effect": "Effect",
          "effect/Layer": "Layer",
          "effect/Option": "Option",
          "solid-js": "Solid",
        },
      },
    },
  },
  resolve: {
    conditions: ["development", "solid", "browser"],
  },
  plugins: [
    tsconfigPaths(),
    tailwindcss(),
    solid(),
    dts({ tsconfigPath: "./tsconfig.build.json" }),
  ],
});
